"""
pdf_builder.py

Builds the professional financial research report PDF.
Part 1
"""

from pathlib import Path
from datetime import datetime

from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
)

from formatter import ReportFormatter
from analysis import FinancialAnalysis
from tables import ReportTables
from charts import ChartGenerator
from styles import ReportStyles
from models import ReportData


class PDFBuilder:
    """
    Responsible for building the complete analyst report.
    """

    def __init__(self):

        self.styles = ReportStyles()
        self.tables = ReportTables()
        self.charts = ChartGenerator()

        self.story = []

    # -----------------------------------------------------
    # Header & Footer
    # -----------------------------------------------------

    @staticmethod
    def _header_footer(canvas, doc):

        canvas.saveState()

        width, height = doc.pagesize

        # Header

        canvas.setFont("Helvetica-Bold", 10)

        canvas.drawString(
            40,
            height - 35,
            "Multi-Agent Financial Research System"
        )

        # Footer

        canvas.setFont("Helvetica", 9)

        canvas.drawString(
            40,
            25,
            "Generated by Report Agent"
        )

        canvas.drawRightString(
            width - 40,
            25,
            f"Page {doc.page}"
        )

        canvas.restoreState()

    # -----------------------------------------------------
    # Cover Page
    # -----------------------------------------------------

    def add_cover_page(self, report: ReportData):

        self.story.append(
            Spacer(1, 1.2 * inch)
        )

        self.story.append(
            Paragraph(
                "MULTI-AGENT FINANCIAL RESEARCH REPORT",
                self.styles.title,
            )
        )

        self.story.append(
            Paragraph(
                report.extraction.company_name,
                self.styles.subtitle,
            )
        )

        self.story.append(
            Spacer(1, 0.6 * inch)
        )

        generated = datetime.now().strftime("%d %B %Y")

        self.story.append(
            Paragraph(
                f"<b>Generated Date:</b> {generated}",
                self.styles.body,
            )
        )

        self.story.append(
            Paragraph(
                "<b>Generated By:</b> Multi-Agent Financial Research System",
                self.styles.body,
            )
        )

        self.story.append(
            Spacer(1, 0.8 * inch)
        )

        self.story.append(
            Paragraph(
                "Professional Financial Research Report",
                self.styles.heading1,
            )
        )

        self.story.append(
            Paragraph(
                "This report has been automatically generated using outputs "
                "from the Extraction Agent, Red Flag Agent, Comparison Agent "
                "and Research Agent.",
                self.styles.body,
            )
        )

        self.story.append(PageBreak())

    # -----------------------------------------------------
    # Table of Contents
    # -----------------------------------------------------

    def add_table_of_contents(self):

        self.story.append(
            Paragraph(
                "Table of Contents",
                self.styles.heading1,
            )
        )

        sections = [
            "Executive Summary",
            "Company Overview",
            "Financial Performance Analysis",
            "Financial Ratio Analysis",
            "Charts & Visualisations",
            "Risk Assessment",
            "SWOT Analysis",
            "Company Comparison",
            "Research Findings",
            "Investment Outlook",
            "Key Takeaways",
            "Conclusion",
            "Appendix",
        ]

        for section in sections:

            self.story.append(
                Paragraph(
                    f"• {section}",
                    self.styles.body,
                )
            )

        self.story.append(PageBreak())

    # -----------------------------------------------------
    # Executive Summary
    # -----------------------------------------------------

    def add_executive_summary(self, report: ReportData):

        self.story.append(
            Paragraph(
                "Executive Summary",
                self.styles.heading1,
            )
        )

        summary = ReportFormatter.executive_summary(report)

        self.story.append(
            Paragraph(
                summary,
                self.styles.body,
            )
        )

        self.story.append(
            Spacer(1, 18)
        )

    # -----------------------------------------------------
    # Company Overview
    # -----------------------------------------------------

    def add_company_overview(self, report: ReportData):

        self.story.append(
            Paragraph(
                "Company Overview",
                self.styles.heading1,
            )
        )

        overview = ReportFormatter.company_overview(report)

        self.story.append(
            Paragraph(
                overview.replace("\n", "<br/>"),
                self.styles.body,
            )
        )

        self.story.append(
            Spacer(1, 20)
        )

#part-2

    # -----------------------------------------------------
    # Financial Performance Analysis
    # -----------------------------------------------------

    def add_financial_performance(self, report: ReportData):

        self.story.append(
            Paragraph(
                "Financial Performance Analysis",
                self.styles.heading1,
            )
        )

        analysis = FinancialAnalysis.performance_analysis(report)

        for item in analysis:
            self.story.append(
                Paragraph(item, self.styles.body)
            )
            self.story.append(Spacer(1, 8))

        self.story.append(Spacer(1, 16))

    # -----------------------------------------------------
    # Financial Metrics Table
    # -----------------------------------------------------

    def add_financial_metrics_table(self, report: ReportData):

        self.story.append(
            Paragraph(
                "Key Financial Metrics",
                self.styles.heading1,
            )
        )

        table = self.tables.financial_metrics_table(report)

        self.story.append(table)

        self.story.append(Spacer(1, 20))

    # -----------------------------------------------------
    # Financial Ratio Analysis
    # -----------------------------------------------------

    def add_ratio_analysis(self, report: ReportData):

        self.story.append(
            Paragraph(
                "Financial Ratio Analysis",
                self.styles.heading1,
            )
        )

        ratios = FinancialAnalysis.ratio_analysis(report)

        for ratio in ratios:
            self.story.append(
                Paragraph(ratio.replace("\n", "<br/>"), self.styles.body)
            )
            self.story.append(Spacer(1, 8))

        self.story.append(Spacer(1, 16))

    # -----------------------------------------------------
    # Financial Ratio Table
    # -----------------------------------------------------

    def add_ratio_table(self, report: ReportData):

        self.story.append(
            Paragraph(
                "Financial Ratio Summary",
                self.styles.heading1,
            )
        )

        table = self.tables.financial_ratio_table(report)

        self.story.append(table)

        self.story.append(Spacer(1, 20))

#part-3

    # -----------------------------------------------------
    # Charts & Visualisations
    # -----------------------------------------------------

    def add_charts(self, report: ReportData):

        from reportlab.platypus import Image

        self.story.append(
            Paragraph(
                "Charts & Visualisations",
                self.styles.heading1,
            )
        )

        chart_paths = self.charts.generate_all(report)

        for chart in chart_paths:

            if chart is None:
                continue

            try:
                image = Image(str(chart))
                image.drawWidth = 6 * inch
                image.drawHeight = 4 * inch

                self.story.append(image)
                self.story.append(Spacer(1, 18))

            except Exception:
                continue

    # -----------------------------------------------------
    # Risk Assessment
    # -----------------------------------------------------

    def add_risk_assessment(self, report: ReportData):

        self.story.append(
            Paragraph(
                "Risk Assessment",
                self.styles.heading1,
            )
        )

        risks = FinancialAnalysis.risk_assessment(report)

        for risk in risks:

            text = (
                f"<b>{risk['Category']}</b><br/>"
                f"<b>Severity:</b> {risk['Severity']}<br/>"
                f"{risk['Description']}"
            )

            self.story.append(
                Paragraph(text, self.styles.body)
            )

            self.story.append(
                Spacer(1, 8)
            )

        self.story.append(Spacer(1, 12))

    # -----------------------------------------------------
    # Risk Summary Table
    # -----------------------------------------------------

    def add_risk_table(self, report: ReportData):

        self.story.append(
            Paragraph(
                "Risk Summary",
                self.styles.heading2,
            )
        )

        table = self.tables.risk_table(report)

        self.story.append(table)

        self.story.append(
            Spacer(1, 18)
        )

    # -----------------------------------------------------
    # SWOT Analysis
    # -----------------------------------------------------

    def add_swot_analysis(self, report: ReportData):

        swot = FinancialAnalysis.swot_analysis(report)

        self.story.append(
            Paragraph(
                "SWOT Analysis",
                self.styles.heading1,
            )
        )

        for section, items in swot.items():

            self.story.append(
                Paragraph(
                    section,
                    self.styles.heading2,
                )
            )

            if not items:

                self.story.append(
                    Paragraph(
                        "Information not available.",
                        self.styles.body,
                    )
                )

            else:

                for item in items:

                    self.story.append(
                        Paragraph(
                            f"• {item}",
                            self.styles.body,
                        )
                    )

            self.story.append(
                Spacer(1, 10)
            ) 

#part-4

    # -----------------------------------------------------
    # Company Comparison
    # -----------------------------------------------------

    def add_company_comparison(self, report: ReportData):

        self.story.append(
            Paragraph(
                "Company Comparison",
                self.styles.heading1,
            )
        )

        self.story.append(
            Paragraph(
                "The following table compares the company's financial "
                "performance against the available peer companies.",
                self.styles.body,
            )
        )

        self.story.append(Spacer(1, 10))

        table = self.tables.comparison_table(report)

        self.story.append(table)

        self.story.append(Spacer(1, 20))

    # -----------------------------------------------------
    # Research Findings
    # -----------------------------------------------------

    def add_research_findings(self, report: ReportData):

        self.story.append(
            Paragraph(
                "Research Findings",
                self.styles.heading1,
            )
        )

        self.story.append(
            Paragraph(
                "The following findings were generated by the Research "
                "Agent using retrieval-augmented generation with source "
                "citations.",
                self.styles.body,
            )
        )

        self.story.append(Spacer(1, 10))

        table = self.tables.research_table(report)

        self.story.append(table)

        self.story.append(Spacer(1, 20))

    # -----------------------------------------------------
    # Investment Outlook
    # -----------------------------------------------------

    def add_investment_outlook(self, report: ReportData):

        self.story.append(
            Paragraph(
                "Investment Outlook",
                self.styles.heading1,
            )
        )

        outlook = FinancialAnalysis.investment_outlook(report)

        self.story.append(
            Paragraph(
                outlook,
                self.styles.body,
            )
        )

        self.story.append(Spacer(1, 20))

    # -----------------------------------------------------
    # Key Takeaways
    # -----------------------------------------------------

    def add_key_takeaways(self, report: ReportData):

        self.story.append(
            Paragraph(
                "Key Takeaways",
                self.styles.heading1,
            )
        )

        takeaways = ReportFormatter.key_takeaways(report)

        for point in takeaways:

            self.story.append(
                Paragraph(
                    f"• {point}",
                    self.styles.body,
                )
            )

        self.story.append(Spacer(1, 20))

    # -----------------------------------------------------
    # Conclusion
    # -----------------------------------------------------

    def add_conclusion(self, report: ReportData):

        self.story.append(
            Paragraph(
                "Conclusion",
                self.styles.heading1,
            )
        )

        company = report.extraction.company_name

        conclusion = (
            f"The financial information available for {company} has been "
            f"successfully analysed using the Multi-Agent Financial "
            f"Research System. This report combines structured financial "
            f"data, detected risks, company benchmarking and research "
            f"findings into a single analyst-style document.\n\n"
            f"The results should be interpreted alongside industry trends, "
            f"macroeconomic conditions and future company disclosures. "
            f"This report is intended for educational and analytical "
            f"purposes and does not constitute investment advice."
        )

        self.story.append(
            Paragraph(
                conclusion,
                self.styles.body,
            )
        )

        self.story.append(PageBreak())

#part-5

    # -----------------------------------------------------
    # Appendix
    # -----------------------------------------------------

    def add_appendix(self, report: ReportData):

        self.story.append(
            Paragraph(
                "Appendix",
                self.styles.heading1,
            )
        )

        self.story.append(
            Paragraph(
                "This appendix contains all extracted financial metrics, "
                "generated tables, research citations, and supporting charts.",
                self.styles.body,
            )
        )

        self.story.append(Spacer(1, 12))

        self.story.append(
            Paragraph(
                "Extracted Financial Metrics",
                self.styles.heading2,
            )
        )

        self.story.append(
            self.tables.financial_metrics_table(report)
        )

        self.story.append(Spacer(1, 15))

        self.story.append(
            Paragraph(
                "Financial Ratios",
                self.styles.heading2,
            )
        )

        self.story.append(
            self.tables.financial_ratio_table(report)
        )

        self.story.append(Spacer(1, 15))

        self.story.append(
            Paragraph(
                "Research Citations",
                self.styles.heading2,
            )
        )

        self.story.append(
            self.tables.research_table(report)
        )

        self.story.append(PageBreak())

    # -----------------------------------------------------
    # Build PDF
    # -----------------------------------------------------

    def build(self, report: ReportData, output_file: str):

        output_path = Path(output_file)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        document = SimpleDocTemplate(
            str(output_path),
            rightMargin=40,
            leftMargin=40,
            topMargin=50,
            bottomMargin=40,
        )

        # Generate charts first
        self.charts.generate_all(report)

        # Build report sections
        self.add_cover_page(report)
        self.add_table_of_contents()
        self.add_executive_summary(report)
        self.add_company_overview(report)

        self.add_financial_performance(report)
        self.add_financial_metrics_table(report)

        self.add_ratio_analysis(report)
        self.add_ratio_table(report)

        self.add_charts(report)

        self.add_risk_assessment(report)
        self.add_risk_table(report)

        self.add_swot_analysis(report)

        self.add_company_comparison(report)

        self.add_research_findings(report)

        self.add_investment_outlook(report)

        self.add_key_takeaways(report)

        self.add_conclusion(report)

        self.add_appendix(report)

        document.build(
            self.story,
            onFirstPage=self._header_footer,
            onLaterPages=self._header_footer,
        )

        print(f"Report successfully generated at: {output_path}")                