import type {
  AgentInfo,
  CompanyFinancials,
  RedFlag,
  ResearchSession,
  ChatMessage,
} from './types';

export const AGENTS: AgentInfo[] = [
  {
    id: 'document',
    name: 'Document Agent',
    icon: 'FileText',
    description: 'Ingests and prepares financial documents for analysis.',
    responsibilities: [
      'Document Upload',
      'PDF Parsing',
      'Text Cleaning',
      'Intelligent Chunking',
      'Embedding Generation',
      'ChromaDB Indexing',
    ],
    status: 'completed',
    progress: 100,
  },
  {
    id: 'extraction',
    name: 'Extraction Agent',
    icon: 'TableProperties',
    description: 'Extracts structured financial metrics from filings.',
    responsibilities: [
      'Revenue',
      'Net Income',
      'Assets',
      'Liabilities',
      'Financial Ratios',
      'KPIs',
    ],
    status: 'completed',
    progress: 100,
  },
  {
    id: 'redflag',
    name: 'Red Flag Agent',
    icon: 'ShieldAlert',
    description: 'Detects financial anomalies and risk indicators.',
    responsibilities: [
      'Rising Debt',
      'Falling Margins',
      'Audit Risks',
      'Financial Anomalies',
      'Compliance Issues',
    ],
    status: 'running',
    progress: 72,
  },
  {
    id: 'comparison',
    name: 'Comparison Agent',
    icon: 'BarChart3',
    description: 'Benchmarks companies across financial metrics.',
    responsibilities: [
      'Company Comparison',
      'Revenue Comparison',
      'Profit Comparison',
      'Ratio Benchmarking',
    ],
    status: 'running',
    progress: 48,
  },
  {
    id: 'research',
    name: 'Research Agent',
    icon: 'BrainCircuit',
    description: 'Powers conversational research with grounded reasoning.',
    responsibilities: ['AI Chat', 'Multi-step Reasoning', 'Source Grounded Answers', 'Financial Insights'],
    status: 'waiting',
    progress: 0,
  },
  {
    id: 'report',
    name: 'Report Agent',
    icon: 'FileCheck2',
    description: 'Synthesizes findings into downloadable reports.',
    responsibilities: ['Executive Summary', 'Investment Analysis', 'Risk Summary', 'PDF Report Generation'],
    status: 'waiting',
    progress: 0,
  },
];

export const PIPELINE_STEPS = [
  { key: 'uploaded', label: 'Document Uploaded' },
  { key: 'parsing', label: 'Parsing' },
  { key: 'chunking', label: 'Chunking' },
  { key: 'embedding', label: 'Embedding Generation' },
  { key: 'indexing', label: 'ChromaDB Indexing' },
];

export const UPLOADED_DOCS = [
  { id: 'd1', name: 'Microsoft_10K_2024.pdf', size: '4.2 MB', company: 'Microsoft', uploadedAt: '2 min ago', status: 'ready' as const },
  { id: 'd2', name: 'Apple_10K_2024.pdf', size: '3.8 MB', company: 'Apple', uploadedAt: '5 min ago', status: 'ready' as const },
  { id: 'd3', name: 'MSFT_Earnings_Q4.pdf', size: '1.1 MB', company: 'Microsoft', uploadedAt: '8 min ago', status: 'ready' as const },
];

export const COMPANIES: CompanyFinancials[] = [
  {
    ticker: 'MSFT',
    name: 'Microsoft',
    revenue: 245.1,
    netIncome: 88.1,
    assets: 512.2,
    liabilities: 286.8,
    debt: 97.4,
    operatingMargin: 44.7,
    cashFlow: 118.5,
    eps: 11.8,
    revenueHistory: [168, 203, 211, 245],
    profitHistory: [61, 72, 82, 88],
    sector: 'Technology',
  },
  {
    ticker: 'AAPL',
    name: 'Apple',
    revenue: 383.3,
    netIncome: 97.0,
    assets: 352.8,
    liabilities: 258.5,
    debt: 111.1,
    operatingMargin: 30.0,
    cashFlow: 110.5,
    eps: 6.1,
    revenueHistory: [365, 394, 383, 383],
    profitHistory: [95, 100, 97, 97],
    sector: 'Technology',
  },
  {
    ticker: 'GOOGL',
    name: 'Alphabet',
    revenue: 307.4,
    netIncome: 73.8,
    assets: 450.3,
    liabilities: 228.1,
    debt: 28.1,
    operatingMargin: 27.2,
    cashFlow: 84.3,
    eps: 5.8,
    revenueHistory: [257, 282, 307, 307],
    profitHistory: [76, 60, 73, 74],
    sector: 'Technology',
  },
  {
    ticker: 'AMZN',
    name: 'Amazon',
    revenue: 574.8,
    netIncome: 30.4,
    assets: 531.5,
    liabilities: 326.4,
    debt: 135.6,
    operatingMargin: 8.1,
    cashFlow: 84.9,
    eps: 2.9,
    revenueHistory: [469, 513, 574, 575],
    profitHistory: [33, 24, 30, 30],
    sector: 'Consumer',
  },
];

export const RED_FLAGS: RedFlag[] = [
  {
    id: 'rf1',
    title: 'High Debt Level',
    severity: 'critical',
    company: 'Amazon',
    description: 'Total debt has risen 18% YoY, increasing leverage risk and interest burden.',
    metric: 'Debt-to-Equity',
    value: '2.14',
    trend: 'up',
  },
  {
    id: 'rf2',
    title: 'Negative Free Cash Flow',
    severity: 'high',
    company: 'Alphabet',
    description: 'CapEx surge reduced free cash flow in the most recent quarter.',
    metric: 'Free Cash Flow',
    value: '-$4.2B',
    trend: 'down',
  },
  {
    id: 'rf3',
    title: 'Declining Revenue',
    severity: 'high',
    company: 'Apple',
    description: 'Revenue contracted 2.8% year-over-year, driven by iPhone softness.',
    metric: 'Revenue Growth',
    value: '-2.8%',
    trend: 'down',
  },
  {
    id: 'rf4',
    title: 'Audit Qualification',
    severity: 'medium',
    company: 'Amazon',
    description: 'Auditor flagged revenue recognition timing for AWS contracts.',
    metric: 'Audit Opinion',
    value: 'Qualified',
    trend: 'up',
  },
  {
    id: 'rf5',
    title: 'Legal Risk Exposure',
    severity: 'medium',
    company: 'Alphabet',
    description: 'Ongoing antitrust proceedings may impact ad revenue model.',
    metric: 'Contingent Liability',
    value: '$3.1B',
    trend: 'up',
  },
  {
    id: 'rf6',
    title: 'Liquidity Concerns',
    severity: 'high',
    company: 'Amazon',
    description: 'Current ratio fell below 1.0, signaling short-term liquidity strain.',
    metric: 'Current Ratio',
    value: '0.97',
    trend: 'down',
  },
];

export const RESEARCH_SESSIONS: ResearchSession[] = [
  {
    id: 's1',
    name: 'Big Tech Q4 Comparison',
    companies: ['Microsoft', 'Apple', 'Alphabet', 'Amazon'],
    uploadDate: 'Aug 5, 2026',
    documents: 7,
    status: 'completed',
  },
  {
    id: 's2',
    name: 'Microsoft Deep Dive',
    companies: ['Microsoft'],
    uploadDate: 'Aug 3, 2026',
    documents: 3,
    status: 'completed',
  },
  {
    id: 's3',
    name: 'Cloud Sector Analysis',
    companies: ['Microsoft', 'Alphabet', 'Amazon'],
    uploadDate: 'Aug 1, 2026',
    documents: 5,
    status: 'in-progress',
  },
  {
    id: 's4',
    name: 'Apple Earnings Review',
    companies: ['Apple'],
    uploadDate: 'Jul 28, 2026',
    documents: 2,
    status: 'completed',
  },
  {
    id: 's5',
    name: 'Streaming Wars Benchmark',
    companies: ['Netflix', 'Alphabet', 'Amazon'],
    uploadDate: 'Jul 24, 2026',
    documents: 4,
    status: 'queued',
  },
  {
    id: 's6',
    name: 'Semiconductor Outlook',
    companies: ['NVIDIA', 'AMD', 'Intel'],
    uploadDate: 'Jul 20, 2026',
    documents: 6,
    status: 'completed',
  },
];

export const INITIAL_CHAT: ChatMessage[] = [
  {
    id: 'm1',
    role: 'assistant',
    content:
      "Welcome to FinSight AI. I've analyzed the 10-K filings you uploaded for Microsoft, Apple, Alphabet, and Amazon. Ask me anything — I'll ground every answer in the source documents with citations.",
    timestamp: '10:24 AM',
  },
];

export const SUGGESTED_PROMPTS = [
  'Compare Microsoft and Apple',
  'Show revenue growth trends',
  'Identify financial risks',
  'Generate investment summary',
];

export const STATS = {
  documentsUploaded: 24,
  activeSessions: 3,
  reportsGenerated: 11,
  questionsAnswered: 147,
};

export const RECENT_COMPANIES = [
  { name: 'Microsoft', ticker: 'MSFT', filings: 3, color: 'brand' },
  { name: 'Apple', ticker: 'AAPL', filings: 2, color: 'accent' },
  { name: 'Alphabet', ticker: 'GOOGL', filings: 2, color: 'brand' },
  { name: 'Amazon', ticker: 'AMZN', filings: 2, color: 'accent' },
];
